// maidsData.js
export const maidsData = [
    {
      id: 1,
      name: 'Sunita Sharma',
      age: 32,
      religion: 'Hindu',
      experience: '5 years',
      hours: 8, 
      image: 'https://img.freepik.com/free-photo/chambermaid-preparing-hotel-room_23-2148095204.jpg?w=740',
    },

    {
        id: 2,
        name: 'Sunita Sharma',
        age: 32,
        religion: 'Hindu',
        experience: '5 years',
        hours: 8, 
        image: 'https://img.freepik.com/free-photo/chambermaid-preparing-hotel-room_23-2148095204.jpg?w=740',
      },
      {
        id: 3,
        name: 'Sunita Sharma',
        age: 32,
        religion: 'Hindu',
        experience: '5 years',
        hours: 8, 
        image: 'https://img.freepik.com/free-photo/chambermaid-preparing-hotel-room_23-2148095204.jpg?w=740',
      },
      {
        id: 4,
        name: 'Sunita Sharma',
        age: 32,
        religion: 'Hindu',
        experience: '5 years',
        hours: 8, 
        image: 'https://img.freepik.com/free-photo/chambermaid-preparing-hotel-room_23-2148095204.jpg?w=740',
      },
      {
        id: 5,
        name: 'Sunita Sharma',
        age: 32,
        religion: 'Hindu',
        experience: '5 years',
        hours: 8, 
        image: 'https://img.freepik.com/free-photo/chambermaid-preparing-hotel-room_23-2148095204.jpg?w=740',
      },

    {
      id: 6,
      name: 'Fatima Begum',
      age: 28,
      religion: 'Muslim',
      experience: '3 years',
      hours: 10, 
      image: 'https://img.freepik.com/free-photo/chambermaid-preparing-hotel-room_23-2148095204.jpg?w=740',
    },
    {
        id: 7,
        name: 'Fatima Begum',
        age: 28,
        religion: 'Muslim',
        experience: '3 years',
        hours: 10, 
        image: 'https://img.freepik.com/free-photo/chambermaid-preparing-hotel-room_23-2148095204.jpg?w=740',
      },
      {
        id: 8,
        name: 'Fatima Begum',
        age: 28,
        religion: 'Muslim',
        experience: '3 years',
        hours: 10, 
        image: 'https://img.freepik.com/free-photo/chambermaid-preparing-hotel-room_23-2148095204.jpg?w=740',
      },
    {
      id: 9,
      name: 'Anjali Kumari',
      age: 40,
      religion: 'Christian',
      experience: '10 years',
      hours: 8, 
      image: 'https://img.freepik.com/free-photo/chambermaid-preparing-hotel-room_23-2148095204.jpg?w=740',
    },
  ];
  